// JavaScript Document
function refresh_item3(face_href,face,face_img,jineng_item,jineng_price,jineng_person,shen_renzheng,xue_renzheng,jineng_dec,jineng_huibao,a_href,jineng_pic1,jineng_pic2,jineng_pic3){
		var str='<table width="100%" border="0" cellspacing="7" cellpadding="4"><tr><td width="8%"><div><div class="face_div"><a id="face_href" href='+face_href+'><img class="face" src='+face+'/></a></div><img class="face_img" src='+face_img+'/></div></td><td width="92%"><table width="100%" border="0" cellspacing="0" cellpadding="3"><tr><td width="24%" class="jineng_title">技能</td><td width="58%" class="jineng_item">'+jineng_item+'</td><td width="18%" class="jineng_price">'+jineng_price+'</td></tr><tr><td class="jineng_person">'+jineng_person+'</td><td>'+'<img class="jineng_renzheng" src='+shen_renzheng+'/><img class="jineng_renzheng" src='+xue_renzheng+'/>'+'</td></tr></table></td></tr><tr><td></td><td align="left">'+'<img class="jineng_pic" src='+jineng_pic1+'/>&nbsp;<img class="jineng_pic" src='+jineng_pic2+'/>&nbsp;<img class="jineng_pic" src='+jineng_pic3+'/>&nbsp;</td></tr><tr><td></td><td class="jineng_dec" align="left">'+jineng_dec+'</td></tr><tr><td></td><td><p id="jineng_award" class="jineng_award">我要</p><div class="jineng_huibao">'+jineng_huibao+'</div></td></tr><tr><td colspan="2" align="right"><a id="tiaozhuan" href='+a_href+'><img src="images/ydu.gif" /></a></td></tr></table><div class="fengexian"></div>';
		$(str).prependTo("#jiazai");
		
	}									
	function refresh_item2(face_href,face,face_img,jineng_item,jineng_price,jineng_person,shen_renzheng,xue_renzheng,jineng_dec,jineng_huibao,a_href,jineng_pic1,jineng_pic2){
		var str='<table width="100%" border="0" cellspacing="7" cellpadding="4"><tr><td width="8%"><div><div class="face_div"><a id="face_href" href='+face_href+'><img class="face" src='+face+'/></a></div><img class="face_img" src='+face_img+'/></div></td><td width="92%"><table width="100%" border="0" cellspacing="0" cellpadding="3"><tr><td width="24%" class="jineng_title">技能</td><td width="58%" class="jineng_item">'+jineng_item+'</td><td width="18%" class="jineng_price">'+jineng_price+'</td></tr><tr><td class="jineng_person">'+jineng_person+'</td><td>'+'<img class="jineng_renzheng" src='+shen_renzheng+'/><img class="jineng_renzheng" src='+xue_renzheng+'/>'+'</td></tr></table></td></tr><tr><td></td><td align="left">'+'<img class="jineng_pic" src='+jineng_pic1+'/>&nbsp;<img class="jineng_pic" src='+jineng_pic2+'/>&nbsp;</td></tr><tr><td></td><td class="jineng_dec" align="left">'+jineng_dec+'</td></tr><tr><td></td><td><p id="jineng_award" class="jineng_award">我要</p><div class="jineng_huibao">'+jineng_huibao+'</div></td></tr><tr><td colspan="2" align="right"><a id="tiaozhuan" href='+a_href+'><img src="images/ydu.gif" /></a></td></tr></table><div class="fengexian"></div>';
		$(str).prependTo("#jiazai");
		
	}									
	function refresh_item1(face_href,face,face_img,jineng_item,jineng_price,jineng_person,shen_renzheng,xue_renzheng,jineng_dec,jineng_huibao,a_href,jineng_pic1){
		var str='<table width="100%" border="0" cellspacing="7" cellpadding="4"><tr><td width="8%"><div><div class="face_div"><a id="face_href" href='+face_href+'><img class="face" src='+face+'/></a></div><img class="face_img" src='+face_img+'/></div></td><td width="92%"><table width="100%" border="0" cellspacing="0" cellpadding="3"><tr><td width="24%" class="jineng_title">技能</td><td width="58%" class="jineng_item">'+jineng_item+'</td><td width="18%" class="jineng_price">'+jineng_price+'</td></tr><tr><td class="jineng_person">'+jineng_person+'</td><td>'+'<img class="jineng_renzheng" src='+shen_renzheng+'/><img class="jineng_renzheng" src='+xue_renzheng+'/>'+'</td></tr></table></td></tr><tr><td></td><td align="left">'+'<img class="jineng_pic" src='+jineng_pic1+'/>&nbsp;</td></tr><tr><td></td><td class="jineng_dec" align="left">'+jineng_dec+'</td></tr><tr><td></td><td><p id="jineng_award" class="jineng_award">我要</p><div class="jineng_huibao">'+jineng_huibao+'</div></td></tr><tr><td colspan="2" align="right"><a id="tiaozhuan" href='+a_href+'><img src="images/ydu.gif" /></a></td></tr></table><div class="fengexian"></div>';
		$(str).prependTo("#jiazai");
	}
	function refresh_item(face_href,face,face_img,jineng_item,jineng_price,jineng_person,shen_renzheng,xue_renzheng,jineng_dec,jineng_huibao,a_href){
		var str='<table width="100%" border="0" cellspacing="7" cellpadding="4"><tr><td width="8%"><div><div class="face_div"><a id="face_href" href='+face_href+'><img class="face" src='+face+'/></a></div><img class="face_img" src='+face_img+'/></div></td><td width="92%"><table width="100%" border="0" cellspacing="0" cellpadding="3"><tr><td width="24%" class="jineng_title">技能</td><td width="58%" class="jineng_item">'+jineng_item+'</td><td width="18%" class="jineng_price">'+jineng_price+'</td></tr><tr><td class="jineng_person">'+jineng_person+'</td><td>'+'<img class="jineng_renzheng" src='+shen_renzheng+'/><img class="jineng_renzheng" src='+xue_renzheng+'/>'+'</td></tr></table></td></tr><tr><td></td></tr><tr><td></td><td class="jineng_dec" align="left">'+jineng_dec+'</td></tr><tr><td></td><td><p id="jineng_award" class="jineng_award">我要</p><div class="jineng_huibao">'+jineng_huibao+'</div></td></tr><tr><td colspan="2" align="right"><a id="tiaozhuan" href='+a_href+'><img src="images/ydu.gif" /></a></td></tr></table><div class="fengexian"></div>';
		$(str).prependTo("#jiazai");
	}			